<a href="https://colab.research.google.com/github/ratimayy/ML/blob/main/HW_plotly_graph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.statista.com/statistics/264362/leading-car-brands-in-the-us-based-on-vehicle-sales/#:~:text=The%20top%20three%20U.S.%20car,sales%20was%20attributable%20to%20its

In [60]:
import pandas as pd
import plotly.express as px
import seaborn as sns

df = pd.read_csv('https://raw.githubusercontent.com/ratimayy/tools/main/car.csv')
df.head()

,Brand,Q2 2021,Q3 2021,Q4 2021,Q1 2022,Q2 2022,Q3 2022,Q4 2022,Q1 2023,Q2 2023,Q3 2023,Q4 2023,Q1 2024
0,Acura,"50,496","38,555","30,469","28,236","24,624","21,792","27,654","33,465","40,177","36,893","35,120","18,305"
1,Alfa Romeo,"5,019","4,530","4,056","3,288","3,084","3,439","3,032","2,390","2,310","2,890","3,307",0
2,Audi,"66,084","41,010","33,180","35,508","49,642","38,667","54,052","52,582","55,608","59,262","59,706",0
3,BMW,"96,561","75,620","93,033","73,712","78,903","78,029","100,899","81,877","87,942","83,954","107,881",0
4,Buick,"65,921","39,298","31,407","19,145","28,878","28,524","26,921","38,138","42,753","43,799","42,162",0

In [65]:
a = df[(df['Brand']=='Ford') | (df['Brand']=='Toyota') | (df['Brand']=='Chevrolet') | (df['Brand']=='Honda') | (df['Brand']=='Nissan')]
a

,Brand,Q2 2021,Q3 2021,Q4 2021,Q1 2022,Q2 2022,Q3 2022,Q4 2022,Q1 2023,Q2 2023,Q3 2023,Q4 2023,Q1 2024
6,Chevrolet,"431,583","286,257","287,136","342,619","383,816","371,415","415,025","397,118","452,678","450,912","401,992",0
10,Ford,"448,745","380,606","483,171","410,026","456,813","441,487","459,175","457,481","507,751","476,725","462,081","309,461"
13,Honda,"435,923","307,359","255,991","238,182","215,165","200,258","227,596","251,042","306,848","296,310","302,391","184,915"
28,Nissan,"280,283","188,291","184,035","189,839","172,620","142,848","177,442","220,058","227,824","200,333","185,876",0
35,Toyota,"573,109","433,299","383,896","433,439","416,834","421,932","456,555","399,070","476,889","508,482","504,500","302,498"

In [66]:
a.drop('Q1 2024', axis = 1, inplace = True)
a

<ipython-input-66-78549c658791>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Brand,Q2 2021,Q3 2021,Q4 2021,Q1 2022,Q2 2022,Q3 2022,Q4 2022,Q1 2023,Q2 2023,Q3 2023,Q4 2023
6,Chevrolet,"431,583","286,257","287,136","342,619","383,816","371,415","415,025","397,118","452,678","450,912","401,992"
10,Ford,"448,745","380,606","483,171","410,026","456,813","441,487","459,175","457,481","507,751","476,725","462,081"
13,Honda,"435,923","307,359","255,991","238,182","215,165","200,258","227,596","251,042","306,848","296,310","302,391"
28,Nissan,"280,283","188,291","184,035","189,839","172,620","142,848","177,442","220,058","227,824","200,333","185,876"
35,Toyota,"573,109","433,299","383,896","433,439","416,834","421,932","456,555","399,070","476,889","508,482","504,500"

In [74]:
b = a.copy()
b.info()
b["Q2 2021"].replace(",","",inplace=True, axis = 0)
b

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 6 to 35
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    5 non-null      object
 1   Q2 2021  5 non-null      object
 2   Q3 2021  5 non-null      object
 3   Q4 2021  5 non-null      object
 4   Q1 2022  5 non-null      object
 5   Q2 2022  5 non-null      object
 6   Q3 2022  5 non-null      object
 7   Q4 2022  5 non-null      object
 8   Q1 2023  5 non-null      object
 9   Q2 2023  5 non-null      object
 10  Q3 2023  5 non-null      object
 11  Q4 2023  5 non-null      object
dtypes: object(12)
memory usage: 520.0+ bytes

TypeError: Series.replace() got an unexpected keyword argument 'axis'

In [63]:
import plotly.express as px

# Melt the DataFrame to convert it to long format
df_long = a.melt(id_vars=["Brand"], var_name="Quarter", value_name="Sales")

# Plot the bar chart using Plotly Express
fig = px.bar(df_long, x="Brand", y="Sales", color="Quarter",
             title="Car Sales by Brand and Quarter",
             labels={"Sales": "Number of Sales", "Brand": "Car Brand", "Quarter": "Quarter"})

# Set the Y-axis range
#fig.update_yaxes(range=[0, 500000])

# Show the plot
fig.show()

In [64]:
Q_counts = df_long.groupby('Quarter', 'Sales']).size().reset_index(name='count')

fig = px.bar(Q_counts,
             x='Brand',
             y='Sales',
             color='Quarter')

fig.show()

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (<ipython-input-64-b19662ca9754>, line 1)