<a href="https://colab.research.google.com/github/ratimayy/ML/blob/main/HW_plotly_graph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.statista.com/statistics/264362/leading-car-brands-in-the-us-based-on-vehicle-sales/#:~:text=The%20top%20three%20U.S.%20car,sales%20was%20attributable%20to%20its

In [18]:
import pandas as pd
import plotly.express as px
import seaborn as sns

df = pd.read_csv('https://raw.githubusercontent.com/ratimayy/tools/main/car_fixed.csv')
df.head()

,Brand,Q2 2021,Q3 2021,Q4 2021,Q1 2022,Q2 2022,Q3 2022,Q4 2022,Q1 2023,Q2 2023,Q3 2023,Q4 2023,Q1 2024
0,Acura,50496,38555,30469,28236,24624,21792,27654,33465,40177,36893,35120,18305
1,Alfa Romeo,5019,4530,4056,3288,3084,3439,3032,2390,2310,2890,3307,0
2,Audi,66084,41010,33180,35508,49642,38667,54052,52582,55608,59262,59706,0
3,BMW,96561,75620,93033,73712,78903,78029,100899,81877,87942,83954,107881,0
4,Buick,65921,39298,31407,19145,28878,28524,26921,38138,42753,43799,42162,0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Brand    38 non-null     object
 1   Q2 2021  38 non-null     int64
 2   Q3 2021  38 non-null     int64
 3   Q4 2021  38 non-null     int64
 4   Q1 2022  38 non-null     int64
 5   Q2 2022  38 non-null     int64
 6   Q3 2022  38 non-null     int64
 7   Q4 2022  38 non-null     int64
 8   Q1 2023  38 non-null     int64
 9   Q2 2023  38 non-null     int64
 10  Q3 2023  38 non-null     int64
 11  Q4 2023  38 non-null     int64
 12  Q1 2024  38 non-null     int64
dtypes: int64(12), object(1)
memory usage: 4.0+ KB

In [20]:
a = df[(df['Brand']=='Ford') | (df['Brand']=='Toyota') | (df['Brand']=='Chevrolet') | (df['Brand']=='Honda') | (df['Brand']=='Nissan')]
a

,Brand,Q2 2021,Q3 2021,Q4 2021,Q1 2022,Q2 2022,Q3 2022,Q4 2022,Q1 2023,Q2 2023,Q3 2023,Q4 2023,Q1 2024
6,Chevrolet,431583,286257,287136,342619,383816,371415,415025,397118,452678,450912,401992,0
10,Ford,448745,380606,483171,410026,456813,441487,459175,457481,507751,476725,462081,309461
13,Honda,435923,307359,255991,238182,215165,200258,227596,251042,306848,296310,302391,184915
28,Nissan,280283,188291,184035,189839,172620,142848,177442,220058,227824,200333,185876,0
35,Toyota,573109,433299,383896,433439,416834,421932,456555,399070,476889,508482,504500,302498

In [21]:
a.drop('Q1 2024', axis = 1, inplace = True)
a

<ipython-input-21-78549c658791>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Brand,Q2 2021,Q3 2021,Q4 2021,Q1 2022,Q2 2022,Q3 2022,Q4 2022,Q1 2023,Q2 2023,Q3 2023,Q4 2023
6,Chevrolet,431583,286257,287136,342619,383816,371415,415025,397118,452678,450912,401992
10,Ford,448745,380606,483171,410026,456813,441487,459175,457481,507751,476725,462081
13,Honda,435923,307359,255991,238182,215165,200258,227596,251042,306848,296310,302391
28,Nissan,280283,188291,184035,189839,172620,142848,177442,220058,227824,200333,185876
35,Toyota,573109,433299,383896,433439,416834,421932,456555,399070,476889,508482,504500

In [22]:
import plotly.express as px

# Melt the DataFrame to convert it to long format
df_long = a.melt(id_vars=["Brand"], var_name="Quarter", value_name="Sales")

# Plot the bar chart using Plotly Express
fig = px.bar(df_long, x="Brand", y="Sales", color="Quarter",
             title="Car Sales by Brand and Quarter in US",
             labels={"Sales": "Number of Sales", "Brand": "Car Brand", "Quarter": "Quarter"})

# Set the Y-axis range
fig.update_yaxes(range=[0, 5000000])

# Show the plot
fig.show()

In [23]:
df_long

        Brand  Quarter   Sales
0   Chevrolet  Q2 2021  431583
1        Ford  Q2 2021  448745
2       Honda  Q2 2021  435923
3      Nissan  Q2 2021  280283
4      Toyota  Q2 2021  573109
5   Chevrolet  Q3 2021  286257
6        Ford  Q3 2021  380606
7       Honda  Q3 2021  307359
8      Nissan  Q3 2021  188291
9      Toyota  Q3 2021  433299
10  Chevrolet  Q4 2021  287136
11       Ford  Q4 2021  483171
12      Honda  Q4 2021  255991
13     Nissan  Q4 2021  184035
14     Toyota  Q4 2021  383896
15  Chevrolet  Q1 2022  342619
16       Ford  Q1 2022  410026
17      Honda  Q1 2022  238182
18     Nissan  Q1 2022  189839
19     Toyota  Q1 2022  433439
20  Chevrolet  Q2 2022  383816
21       Ford  Q2 2022  456813
22      Honda  Q2 2022  215165
23     Nissan  Q2 2022  172620
24     Toyota  Q2 2022  416834
25  Chevrolet  Q3 2022  371415
26       Ford  Q3 2022  441487
27      Honda  Q3 2022  200258
28     Nissan  Q3 2022  142848
29     Toyota  Q3 2022  421932
30  Chevrolet  Q4 2022  415025
31       Ford  Q4 2022  459175
32      Honda  Q4 2022  227596
33     Nissan  Q4 2022  177442
34     Toyota  Q4 2022  456555
35  Chevrolet  Q1 2023  397118
36       Ford  Q1 2023  457481
37      Honda  Q1 2023  251042
38     Nissan  Q1 2023  220058
39     Toyota  Q1 2023  399070
40  Chevrolet  Q2 2023  452678
41       Ford  Q2 2023  507751
42      Honda  Q2 2023  306848
43     Nissan  Q2 2023  227824
44     Toyota  Q2 2023  476889
45  Chevrolet  Q3 2023  450912
46       Ford  Q3 2023  476725
47      Honda  Q3 2023  296310
48     Nissan  Q3 2023  200333
49     Toyota  Q3 2023  508482
50  Chevrolet  Q4 2023  401992
51       Ford  Q4 2023  462081
52      Honda  Q4 2023  302391
53     Nissan  Q4 2023  185876
54     Toyota  Q4 2023  504500